# THIS IS THE DOCKER-COMPOSE FILE FOR PRODUCTION
version: '3.7'

services:
  my_app_db:
    container_name: my_app_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kjslfh87345h932hskdfjjhf8
      POSTGRES_DB: postgres
    # env_file:
    #   ../myapp.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  my_app_backend:
    container_name: my_app_backend
    build:
      context: ..
      target: prod
    image: myappautomation/myapp:latest
    command: /code/deployment-scripts/docker-entrypoint.sh
    env_file:
      ../myapp.env
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - my_app_db

volumes:
  postgres_data:
  letsencrypt: